#!/usr/bin/bash

Clock() {
	DATE=$(date "+%d.%m")
	TIME=$(date "+%H:%M")

	echo -e -n "%{F#bbbbbb} \uf073 ${DATE} %{F-} \uf017 ${TIME} "
}

# ActiveWindow() {
	# echo -n $(xdotool getwindowfocus getwindowname | cut -c -52)
# }

Battery() {
	BATTACPI=$(acpi --battery)
	BATPERC=$(echo $BATTACPI | cut -d, -f2 | tr -d '[:space:]')

	if [[ $BATTACPI == *"100%"* ]]
	then
		echo -e -n "\uf00c $BATPERC"
	elif [[ $BATTACPI == *"Discharging"* ]]
	then
		BATPERC=${BATPERC::-1}
		if [ $BATPERC -le "10" ]
		then
			echo -e -n "%{F#FF5722}\uf244"
		elif [ $BATPERC -le "25" ]
		then
			echo -e -n "%{F#FFC107}\uf243"
		elif [ $BATPERC -le "50" ]
		then
			echo -e -n "\uf242"
		elif [ $BATPERC -le "75" ]
		then
			echo -e -n "\uf241"
		elif [ $BATPERC -le "100" ]
		then
			echo -e -n "\uf240"
		fi
		echo -e " $BATPERC%{F-}"
	elif [[ $BATTACPI == *"Charging"* && $BATTACPI != *"100%"* ]]
	then
		echo -e "\uf0e7 $BATPERC"
	elif [[ $BATTACPI == *"Unknown"* ]]
	then
		echo -e "$BATPERC"
	fi
}

Wifi() {
	#WIFISTR=$( iwconfig wlp3s0 | grep "Link" | sed 's/ //g' | sed 's/LinkQuality=//g' | sed 's/\/.*//g')
	#if [ ! -z $WIFISTR ] ; then
		#WIFISTR=$(( ${WIFISTR} * 100 / 70))
	ESSID=$(iwconfig wlp3s0 | grep ESSID | sed 's/ //g' | sed 's/.*%://' | cut -d "\"" -f 2)
	if [[ $ESSID != *"off"* ]] ; then
		echo -e "| \uf1eb ${ESSID}"
	fi
	#fi
}

Sound(){
	NOTMUTED=$( amixer sget Master | grep "\[on\]" )
	if [[ ! -z $NOTMUTED ]] ; then
		VOL=$((awk -F"[][]" '/\[on\]/ { print $2 }' \
            <(amixer sget Master) | sed 's/%//g') | head -n 1)
		if [ $VOL -ge 70 ] ; then
			echo -e "| %{F#EF5350}\uf028 ${VOL}%{F-}"
		elif [ $VOL -ge 30 ] ; then
			echo -e "| %{F#8BC34A}\uf027 ${VOL}%{F-}"
		else
			echo -e "| %{F#8BC34A}\uf026 ${VOL}%{F-}"
		fi
	else
		echo -e "| %{F#616161}\uf026 M%{F-}"
	fi
}

bspwm_ws() {
	desktop=1
	ws=""
	IFS=':' read -a array <<< $(bspc wm --get-status)
	for item in "${array[@]}"
	do
		name=${item#?}
		if [ "$item" == "LT" ]
		then
			ws="${ws}%{S+}"
		else
			desk=""
			case $item in
				O*) # focused occupied
					desk=" \uf111"
				;;
				F*) # focused free
					desk=" \uf10c"
				;;
				U*) # focused urgent
					desk="%{F#FF7043} \uf111%{F-}"
				;;
				o*) # occupied
					desk="%{F#999999} \uf111%{F-}"
				;;
				f*) # free
					desk="%{F#999999} \uf10c%{F-}"
				;;
				u*) # urgent
					desk="%{F#FF7043} \uf13a%{F-}"
				;;
			esac
			shift
			if [ "$desk" != "" ]
			then
                ws="$ws$desk"
				desktop=$((desktop+1))
			fi
		fi
	done
	ws="${ws}${S0}"
	echo "${ws}"
}

#num_mon=$(bspc query -M | wc -l)
while [ "$(pidof bspwm)" != "" ]; do
	echo -e "%{l} $(Battery) $(Sound) $(Wifi) %{c} $(bspwm_ws) %{r} $(Clock)"
	sleep 0.2s
done
