#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

USR_APP="/usr/share/applications/"

sudo rsync -lu /home/allu/.local/share/applications/*.desktop "$USR_APP"
## does not work in the single user mode of nix
sudo update-desktop-database --verbose
