#! /bin/sh
##run_once is a script in /usr/bin that prevents running script if it is running already
##

## Load appearance settings
xsetroot -cursor_name left_ptr &
export GTK2_RC_FILES="$HOME/.gtkrc-2.0" &
xrdb merge .Xresources &

## Set keyboard repeat and settings
xset r rate 240 38 &
xinput --set-prop 12 "Device Accel Constant Deceleration" 0.5 &

## Wallpaper. Nitrogen just draws wallpaper.
sh ~/.fehbg &

## compositing. Required for shadows, transparency and stuff. 
# Alter compton settings if using intel graphics
GRAPHIC_CARD=$(lspci | grep -i "vga" | sed 's/.*://' | sed 's/(.*//' | sed 's/^[ \t]*//')
if [[ $(echo $GRAPHIC_CARD | grep -i 'intel\|lenovo') != "" ]]; then MCODE='initrd=\intel-ucode.img'
  sed -i 's/"xrender"/"glx"/' ~/.config/compton.conf
  grep -q 'vsync = "opengl-swc";' ~/.config/compton.conf || echo 'vsync = "opengl-swc";' >> ~/.config/compton.conf
fi

## Reduces flicker. Disabling saves resources.
compton -b &

## enable local fonts in .fonts directory
xset +fp /usr/share/fonts/local &
xset +fp /usr/share/fonts/misc &
xset +fp ~/.fonts &
xset fp rehash &
# Disabled by allu, possibly taking too much time to boot up
# fc-cache -fv &

## Automount removable media
devmon &

## powersaving options
xset s off &
xset s noblank &
xset s noexpose &
xset c on &
xset -dpms &
xbacklight -set 15 &

## Run screenlock when suspending
light-locker &

## unclutter the mouse
unclutter &

## Make monitor settings persist between reboots
#eval $(awk -F'=' '/Exec=/ {print $2}' ~/.config/autostart/lxrandr-autostart.desktop) &

## Notify about package updates
update-checker 7200 &

## Map super key to trigger rofi when used alone
xcape -e 'Super_L=Super_L|Shift_L|d' &

## Polkit agent
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

## Gnome keyring
gnome-keyring-daemon &
thunar --daemon &
/usr/lib/mate-notification-daemon/mate-notification-daemon &

##xfce4 power manager for screen dimming and such
xfce4-power-manager &

## Welcome message
sleep 1 && notify-send "Welcome to the Machine!" &

## drop the touchpad
thinkpad-touchpad &
